### ISSUE TITLE
Bottom slice of image issue

### ISSUE THREAD

**Issue by robbwh** [MASILab/SynBOLD-DisCo#1]
Hi,

Just reaching out because you asked for some feedback. On the first test case I tried this out on, the bottom slice appears to suffer from an issue. This is potentially related to incomplete coverage. 

<img width="1514" alt="Screen Shot 2022-09-26 at 7 31 56 PM" src="https://user-images.githubusercontent.com/39274562/192404530-1f80549d-51d6-4cb3-ae4c-27c55f5859ab.png">

You can hopefully see below that the intensity of the bottom slice of BOLD_s_3D is lower/darker
<img width="1493" alt="Screen Shot 2022-09-26 at 7 32 15 PM" src="https://user-images.githubusercontent.com/39274562/192404558-d0f51a5d-5452-4dfa-a60b-96a1454926bc.png">

Then the topup output is wonky on the bottom slice and shifted posteriorly, which you can see most clearly on the sagittal slice:

<img width="1524" alt="Screen Shot 2022-09-26 at 7 34 12 PM" src="https://user-images.githubusercontent.com/39274562/192404749-4274f480-8440-4516-b892-34b28421b3df.png">

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
