### ISSUE TITLE
Introduction of vertical stripes?

### ISSUE THREAD

**Issue by marilenad** [MASILab/SynBOLD-DisCo#7]
Hi,

Thanks for a really cool toolbox! Overall, it seems to work really well for me, however, there's a few participants where vertical stripes are being introduced during the distortion correction. 

![image](https://github.com/MASILab/SynBOLD-DisCo/assets/38101783/bc30d8c8-8cd2-4e51-822b-840fa17d873d)

I am using the containerized version on a cluster. Do you have any suggestions as to what to look at?

Thank you!

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
